/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvidersIndexRouteImport } from './routes/providers/index'
import { Route as ProvidersNewKindRouteImport } from './routes/providers/new.$kind'
import { Route as ProvidersIdEditRouteImport } from './routes/providers/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersNewKindRoute = ProvidersNewKindRouteImport.update({
  id: '/providers/new/$kind',
  path: '/providers/new/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdEditRoute = ProvidersIdEditRouteImport.update({
  id: '/providers/$id/edit',
  path: '/providers/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/providers/new/$kind': typeof ProvidersNewKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/providers/new/$kind': typeof ProvidersNewKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/providers/new/$kind': typeof ProvidersNewKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/providers/' | '/providers/$id/edit' | '/providers/new/$kind'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/providers' | '/providers/$id/edit' | '/providers/new/$kind'
  id:
    | '__root__'
    | '/'
    | '/providers/'
    | '/providers/$id/edit'
    | '/providers/new/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  ProvidersIdEditRoute: typeof ProvidersIdEditRoute
  ProvidersNewKindRoute: typeof ProvidersNewKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/new/$kind': {
      id: '/providers/new/$kind'
      path: '/providers/new/$kind'
      fullPath: '/providers/new/$kind'
      preLoaderRoute: typeof ProvidersNewKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id/edit': {
      id: '/providers/$id/edit'
      path: '/providers/$id/edit'
      fullPath: '/providers/$id/edit'
      preLoaderRoute: typeof ProvidersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  ProvidersIdEditRoute: ProvidersIdEditRoute,
  ProvidersNewKindRoute: ProvidersNewKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
