/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TracesIndexRouteImport } from './routes/traces/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProvidersIndexRouteImport } from './routes/providers/index'
import { Route as PluginsIndexRouteImport } from './routes/plugins/index'
import { Route as TracesTraceIdRouteImport } from './routes/traces/$traceId'
import { Route as ProvidersNewKindRouteImport } from './routes/providers/new.$kind'
import { Route as ProvidersIdEditRouteImport } from './routes/providers/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesIndexRoute = TracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesTraceIdRoute = TracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersNewKindRoute = ProvidersNewKindRouteImport.update({
  id: '/providers/new/$kind',
  path: '/providers/new/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdEditRoute = ProvidersIdEditRouteImport.update({
  id: '/providers/$id/edit',
  path: '/providers/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/plugins/': typeof PluginsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/traces/': typeof TracesIndexRoute
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/providers/new/$kind': typeof ProvidersNewKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/plugins': typeof PluginsIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/traces': typeof TracesIndexRoute
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/providers/new/$kind': typeof ProvidersNewKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/plugins/': typeof PluginsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/traces/': typeof TracesIndexRoute
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/providers/new/$kind': typeof ProvidersNewKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/traces/$traceId'
    | '/plugins/'
    | '/providers/'
    | '/settings/'
    | '/traces/'
    | '/providers/$id/edit'
    | '/providers/new/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/traces/$traceId'
    | '/plugins'
    | '/providers'
    | '/settings'
    | '/traces'
    | '/providers/$id/edit'
    | '/providers/new/$kind'
  id:
    | '__root__'
    | '/'
    | '/traces/$traceId'
    | '/plugins/'
    | '/providers/'
    | '/settings/'
    | '/traces/'
    | '/providers/$id/edit'
    | '/providers/new/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TracesTraceIdRoute: typeof TracesTraceIdRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TracesIndexRoute: typeof TracesIndexRoute
  ProvidersIdEditRoute: typeof ProvidersIdEditRoute
  ProvidersNewKindRoute: typeof ProvidersNewKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/': {
      id: '/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof TracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/$traceId': {
      id: '/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof TracesTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/new/$kind': {
      id: '/providers/new/$kind'
      path: '/providers/new/$kind'
      fullPath: '/providers/new/$kind'
      preLoaderRoute: typeof ProvidersNewKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id/edit': {
      id: '/providers/$id/edit'
      path: '/providers/$id/edit'
      fullPath: '/providers/$id/edit'
      preLoaderRoute: typeof ProvidersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TracesTraceIdRoute: TracesTraceIdRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TracesIndexRoute: TracesIndexRoute,
  ProvidersIdEditRoute: ProvidersIdEditRoute,
  ProvidersNewKindRoute: ProvidersNewKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
