// Reversed from the grok.com client on 2026-09-22
// (cdn.grok.com/_next/static/chunks/3qat1p3pisfyj.js, fileDesc for
// prod/mc/billing-proto/proto/consumer_ui.proto).
// Settings calls ConsumerUiSvc unless ENABLE_BILLING_FACADE is set.
// That flag uses grok_api_v2.GrokBuildBilling instead, which is not this schema.

// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file consumer-ui.proto (package prod_mc_billing, syntax proto3)
/* eslint-disable */

import type { Message } from '@bufbuild/protobuf';
import type { GenFile, GenMessage, GenService } from '@bufbuild/protobuf/codegenv2';
import { fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv2';
import type { Timestamp } from '@bufbuild/protobuf/wkt';
import { file_google_protobuf_timestamp } from '@bufbuild/protobuf/wkt';

/**
 * Describes the file consumer-ui.proto.
 */
export const file_consumer_ui: GenFile /*@__PURE__*/ = fileDesc(
  'ChFjb25zdW1lci11aS5wcm90bxIPcHJvZF9tY19iaWxsaW5nIowBChJDb25zdW1lclJlc2V0VG9rZW4SEAoIdG9rZW5faWQYCiABKAkSMgoOdmFsaWRpdHlfc3RhcnQYFCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjAKDHZhbGlkaXR5X2VuZBgeIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiHwodQ29uc3VtZXJHZXRSZW1haW5pbmdSZXNldHNSZXEiVQoeQ29uc3VtZXJHZXRSZW1haW5pbmdSZXNldHNSZXNwEjMKBnRva2VucxgKIAMoCzIjLnByb2RfbWNfYmlsbGluZy5Db25zdW1lclJlc2V0VG9rZW4iKgoWQ29uc3VtZXJSZWRlZW1SZXNldFJlcRIQCgh0b2tlbl9pZBgKIAEoCSJYChdDb25zdW1lclJlZGVlbVJlc2V0UmVzcBI9ChBzdGlsbF9yZWRlZW1hYmxlGAogAygLMiMucHJvZF9tY19iaWxsaW5nLkNvbnN1bWVyUmVzZXRUb2tlbjLoAQoNQ29uc3VtZXJVaVN2YxJ1ChJHZXRSZW1haW5pbmdSZXNldHMSLi5wcm9kX21jX2JpbGxpbmcuQ29uc3VtZXJHZXRSZW1haW5pbmdSZXNldHNSZXEaLy5wcm9kX21jX2JpbGxpbmcuQ29uc3VtZXJHZXRSZW1haW5pbmdSZXNldHNSZXNwEmAKC1JlZGVlbVJlc2V0EicucHJvZF9tY19iaWxsaW5nLkNvbnN1bWVyUmVkZWVtUmVzZXRSZXEaKC5wcm9kX21jX2JpbGxpbmcuQ29uc3VtZXJSZWRlZW1SZXNldFJlc3BiBnByb3RvMw',
  [file_google_protobuf_timestamp],
);

/**
 * @generated from message prod_mc_billing.ConsumerResetToken
 */
export type ConsumerResetToken = Message<'prod_mc_billing.ConsumerResetToken'> & {
  /**
   * @generated from field: string token_id = 10;
   */
  tokenId: string;

  /**
   * @generated from field: google.protobuf.Timestamp validity_start = 20;
   */
  validityStart?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp validity_end = 30;
   */
  validityEnd?: Timestamp | undefined;
};

/**
 * Describes the message prod_mc_billing.ConsumerResetToken.
 * Use `create(ConsumerResetTokenSchema)` to create a new message.
 */
export const ConsumerResetTokenSchema: GenMessage<ConsumerResetToken> /*@__PURE__*/ = messageDesc(file_consumer_ui, 0);

/**
 * @generated from message prod_mc_billing.ConsumerGetRemainingResetsReq
 */
export type ConsumerGetRemainingResetsReq = Message<'prod_mc_billing.ConsumerGetRemainingResetsReq'> & {};

/**
 * Describes the message prod_mc_billing.ConsumerGetRemainingResetsReq.
 * Use `create(ConsumerGetRemainingResetsReqSchema)` to create a new message.
 */
export const ConsumerGetRemainingResetsReqSchema: GenMessage<ConsumerGetRemainingResetsReq> /*@__PURE__*/ = messageDesc(
  file_consumer_ui,
  1,
);

/**
 * @generated from message prod_mc_billing.ConsumerGetRemainingResetsResp
 */
export type ConsumerGetRemainingResetsResp = Message<'prod_mc_billing.ConsumerGetRemainingResetsResp'> & {
  /**
   * @generated from field: repeated prod_mc_billing.ConsumerResetToken tokens = 10;
   */
  tokens: ConsumerResetToken[];
};

/**
 * Describes the message prod_mc_billing.ConsumerGetRemainingResetsResp.
 * Use `create(ConsumerGetRemainingResetsRespSchema)` to create a new message.
 */
export const ConsumerGetRemainingResetsRespSchema: GenMessage<ConsumerGetRemainingResetsResp> /*@__PURE__*/ =
  messageDesc(file_consumer_ui, 2);

/**
 * @generated from message prod_mc_billing.ConsumerRedeemResetReq
 */
export type ConsumerRedeemResetReq = Message<'prod_mc_billing.ConsumerRedeemResetReq'> & {
  /**
   * @generated from field: string token_id = 10;
   */
  tokenId: string;
};

/**
 * Describes the message prod_mc_billing.ConsumerRedeemResetReq.
 * Use `create(ConsumerRedeemResetReqSchema)` to create a new message.
 */
export const ConsumerRedeemResetReqSchema: GenMessage<ConsumerRedeemResetReq> /*@__PURE__*/ = messageDesc(
  file_consumer_ui,
  3,
);

/**
 * @generated from message prod_mc_billing.ConsumerRedeemResetResp
 */
export type ConsumerRedeemResetResp = Message<'prod_mc_billing.ConsumerRedeemResetResp'> & {
  /**
   * @generated from field: repeated prod_mc_billing.ConsumerResetToken still_redeemable = 10;
   */
  stillRedeemable: ConsumerResetToken[];
};

/**
 * Describes the message prod_mc_billing.ConsumerRedeemResetResp.
 * Use `create(ConsumerRedeemResetRespSchema)` to create a new message.
 */
export const ConsumerRedeemResetRespSchema: GenMessage<ConsumerRedeemResetResp> /*@__PURE__*/ = messageDesc(
  file_consumer_ui,
  4,
);

/**
 * @generated from service prod_mc_billing.ConsumerUiSvc
 */
export const ConsumerUiSvc: GenService<{
  /**
   * @generated from rpc prod_mc_billing.ConsumerUiSvc.GetRemainingResets
   */
  getRemainingResets: {
    methodKind: 'unary';
    input: typeof ConsumerGetRemainingResetsReqSchema;
    output: typeof ConsumerGetRemainingResetsRespSchema;
  };
  /**
   * @generated from rpc prod_mc_billing.ConsumerUiSvc.RedeemReset
   */
  redeemReset: {
    methodKind: 'unary';
    input: typeof ConsumerRedeemResetReqSchema;
    output: typeof ConsumerRedeemResetRespSchema;
  };
}> /*@__PURE__*/ = serviceDesc(file_consumer_ui, 0);
