import { join } from 'node:path';

const SOURCE_DIR = join(import.meta.dir, '..', 'src');

/** Tailwind `--color-olive-950`; the dashboard theme's `--foreground` in light mode. */
const DARK_INK = '#0c0c09';
/** Tailwind `--color-olive-50`; the dashboard theme's `--foreground` in dark mode. */
const LIGHT_INK = '#fbfbf9';

interface Geometry {
  readonly viewBox: string;
  readonly path: string;
}

const readGeometry = async (fileName: string): Promise<Geometry> => {
  const svg = await Bun.file(join(SOURCE_DIR, fileName)).text();
  // Only the first `d` is read, so a multi-path source would be silently truncated.
  const pathTag = /<path\b[^>]*>/g.exec(svg);
  if (svg.match(/<path\b/g)?.length !== 1 || !pathTag) {
    throw new Error(`${fileName} must contain exactly one <path> element`);
  }
  // Only `d` survives into the artifacts. A re-export carrying `fill-rule`, `transform`, or a
  // `clip-path` would render differently and the clean-tree assertion could not see it, because
  // it only compares the generator's output against the generator's own previous output.
  const extra = pathTag[0]
    .slice('<path'.length, -1)
    .replace(/\s(?:d|fill)="[^"]*"/g, '')
    .replace(/\/$/, '')
    .trim();
  if (extra) {
    throw new Error(`${fileName}: <path> carries unsupported attributes (${extra}); only d and fill are used`);
  }
  const viewBox = /viewBox="([^"]*)"/.exec(svg)?.[1];
  const path = /\bd="([^"]*)"/.exec(svg)?.[1];
  if (!viewBox || !path) {
    throw new Error(`${fileName} is missing a viewBox or a path`);
  }
  // The path is embedded in a single-quoted TS string literal in logo-geometry.ts.
  if (/['\\]/.test(path) || /['\\]/.test(viewBox)) {
    throw new Error(`${fileName}: geometry contains a quote or backslash, which would break logo-geometry.ts`);
  }
  return { viewBox, path };
};

const write = async (fileName: string, contents: string): Promise<void> => {
  await Bun.write(join(SOURCE_DIR, fileName), contents);
};

const coloredSvg = ({ viewBox, path }: Geometry, fill: string): string =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}"><title>AIO Proxy</title>` +
  `<path fill="${fill}" d="${path}"/></svg>\n`;

const faviconSvg = ({ viewBox, path }: Geometry): string =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}"><title>AIO Proxy</title>` +
  `<style>#mark{fill:${DARK_INK}}@media (prefers-color-scheme:dark){#mark{fill:${LIGHT_INK}}}</style>` +
  `<path id="mark" d="${path}"/></svg>\n`;

const geometryModule = (wordmark: Geometry, mark: Geometry): string =>
  [
    '// Generated by packages/brand/scripts/build-assets.ts. Do not edit.',
    '',
    `export const WORDMARK_VIEW_BOX = '${wordmark.viewBox}';`,
    '',
    `export const WORDMARK_PATH =\n  '${wordmark.path}';`,
    '',
    `export const MARK_VIEW_BOX = '${mark.viewBox}';`,
    '',
    `export const MARK_PATH =\n  '${mark.path}';`,
    '',
  ].join('\n');

const wordmark = await readGeometry('aio-proxy-wordmark.svg');
const mark = await readGeometry('aio-proxy-mark.svg');

await write('aio-proxy-wordmark-light.svg', coloredSvg(wordmark, DARK_INK));
await write('aio-proxy-wordmark-dark.svg', coloredSvg(wordmark, LIGHT_INK));
await write('aio-proxy-mark-favicon.svg', faviconSvg(mark));
await write('logo-geometry.ts', geometryModule(wordmark, mark));

console.log('Generated 3 SVG artifacts and logo-geometry.ts.');
