import { join } from "node:path";
import {
  type Expression,
  type PropertyAssignment,
  type PropertySignatureDeclaration,
  type Statement,
  NodeFlags,
  SyntaxKind,
  TokenFlags,
} from "typescript/unstable/ast";
import * as factory from "typescript/unstable/ast/factory";
import { API } from "typescript/unstable/async";

type Journal = {
  readonly entries: readonly {
    readonly tag: string;
  }[];
};

type MigrationInput = {
  readonly version: number;
  readonly file: string;
  readonly sha256: string;
};

export type MigrationManifestResult = {
  readonly changed: boolean;
  readonly migrations: number;
};

const exportModifier = factory.createToken(SyntaxKind.ExportKeyword);
const readonlyModifier = factory.createToken(SyntaxKind.ReadonlyKeyword);

export async function writeMigrationManifestFromJournal(root: string): Promise<MigrationManifestResult> {
  const migrationsDir = join(root, "src/db/migrations");
  const journal = (await Bun.file(join(migrationsDir, "meta/_journal.json")).json()) as Journal;
  const migrations = await Promise.all(
    journal.entries.map(async ({ tag }, index): Promise<MigrationInput> => {
      const file = `${tag}.sql`;
      const sql = await Bun.file(join(migrationsDir, file)).bytes();
      const hasher = new Bun.CryptoHasher("sha256");
      hasher.update(sql);
      return {
        version: index + 1,
        file,
        sha256: hasher.digest("hex"),
      };
    }),
  );

  const api = new API({ cwd: join(import.meta.dir, "..") });
  try {
    const snapshot = await api.updateSnapshot({ openProjects: [join(import.meta.dir, "../tsconfig.json")] });
    const project = snapshot.getProjects()[0];
    if (project === undefined) throw new TypeError("TypeScript project is unavailable");
    const printed = await Promise.all(createManifestAst(migrations).map((node) => project.emitter.printNode(node)));
    const output = ["// Generated by `bun run build:migrations`. Do not edit.", ...printed, ""].join("\n");
    const manifestPath = join(root, "src/db/migrations.manifest.ts");
    const manifestFile = Bun.file(manifestPath);
    const current = (await manifestFile.exists()) ? await manifestFile.text() : undefined;
    if (current === output) {
      return { changed: false, migrations: migrations.length };
    }

    await Bun.write(manifestPath, output);
    return { changed: true, migrations: migrations.length };
  } finally {
    api.close();
  }
}

function createManifestAst(migrations: readonly MigrationInput[]): readonly Statement[] {
  const imports = migrations.map(({ file }, index) =>
    factory.createImportDeclaration(
      undefined,
      factory.createImportClause(undefined, factory.createIdentifier(migrationIdentifier(index)), undefined),
      factory.createStringLiteral(`./migrations/${file}?raw`, TokenFlags.None),
    ),
  );
  const migrationType = factory.createTypeAliasDeclaration(
    [exportModifier],
    factory.createIdentifier("Migration"),
    undefined,
    factory.createTypeLiteralNode([
      readonlyProperty("version", SyntaxKind.NumberKeyword),
      readonlyProperty("file", SyntaxKind.StringKeyword),
      readonlyProperty("sha256", SyntaxKind.StringKeyword),
      readonlyProperty("sql", SyntaxKind.StringKeyword),
    ]),
  );
  const migrationArray = factory.createVariableStatement(
    [exportModifier],
    factory.createVariableDeclarationList(
      [
        factory.createVariableDeclaration(
          factory.createIdentifier("MIGRATIONS"),
          undefined,
          factory.createTypeOperatorNode(
            SyntaxKind.ReadonlyKeyword,
            factory.createArrayTypeNode(factory.createTypeReferenceNode(factory.createIdentifier("Migration"))),
          ),
          factory.createArrayLiteralExpression(
            migrations.map(({ version, file, sha256 }, index) =>
              factory.createObjectLiteralExpression(
                [
                  migrationProperty(
                    "version",
                    SyntaxKind.NumberKeyword,
                    factory.createNumericLiteral(String(version), TokenFlags.None),
                  ),
                  migrationProperty(
                    "file",
                    SyntaxKind.StringKeyword,
                    factory.createStringLiteral(file, TokenFlags.None),
                  ),
                  migrationProperty(
                    "sha256",
                    SyntaxKind.StringKeyword,
                    factory.createStringLiteral(sha256, TokenFlags.None),
                  ),
                  migrationProperty(
                    "sql",
                    SyntaxKind.StringKeyword,
                    factory.createIdentifier(migrationIdentifier(index)),
                  ),
                ],
                true,
              ),
            ),
            true,
          ),
        ),
      ],
      NodeFlags.Const,
    ),
  );
  const compiledVersion = factory.createVariableStatement(
    [exportModifier],
    factory.createVariableDeclarationList(
      [
        factory.createVariableDeclaration(
          factory.createIdentifier("COMPILED_SCHEMA_VERSION"),
          undefined,
          undefined,
          factory.createPropertyAccessExpression(
            factory.createIdentifier("MIGRATIONS"),
            undefined,
            factory.createIdentifier("length"),
            NodeFlags.None,
          ),
        ),
      ],
      NodeFlags.Const,
    ),
  );
  return [...imports, migrationType, migrationArray, compiledVersion];
}

function migrationProperty(
  name: string,
  kind: SyntaxKind.NumberKeyword | SyntaxKind.StringKeyword,
  initializer: Expression,
): PropertyAssignment {
  return factory.createPropertyAssignment(
    undefined,
    factory.createIdentifier(name),
    undefined,
    factory.createKeywordTypeNode(kind),
    initializer,
  );
}

function readonlyProperty(
  name: string,
  kind: SyntaxKind.NumberKeyword | SyntaxKind.StringKeyword,
): PropertySignatureDeclaration {
  return factory.createPropertySignatureDeclaration(
    [readonlyModifier],
    factory.createIdentifier(name),
    undefined,
    factory.createKeywordTypeNode(kind),
    factory.createIdentifier("undefined"),
  );
}

function migrationIdentifier(index: number): string {
  return `migration${index}Sql`;
}
