import { join } from "node:path";
import ts from "typescript";

type Journal = {
  readonly entries: readonly {
    readonly tag: string;
  }[];
};

type MigrationInput = {
  readonly version: number;
  readonly file: string;
  readonly sha256: string;
};

export type MigrationManifestResult = {
  readonly changed: boolean;
  readonly migrations: number;
};

const factory = ts.factory;
const exportModifier = factory.createModifier(ts.SyntaxKind.ExportKeyword);
const readonlyModifier = factory.createModifier(ts.SyntaxKind.ReadonlyKeyword);

export async function writeMigrationManifestFromJournal(root: string): Promise<MigrationManifestResult> {
  const migrationsDir = join(root, "src/db/migrations");
  const journal = (await Bun.file(join(migrationsDir, "meta/_journal.json")).json()) as Journal;
  const migrations = await Promise.all(
    journal.entries.map(async ({ tag }, index): Promise<MigrationInput> => {
      const file = `${tag}.sql`;
      const sql = await Bun.file(join(migrationsDir, file)).bytes();
      const hasher = new Bun.CryptoHasher("sha256");
      hasher.update(sql);
      return {
        version: index + 1,
        file,
        sha256: hasher.digest("hex"),
      };
    }),
  );

  const manifestPath = join(root, "src/db/migrations.manifest.ts");
  const output = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed }).printFile(createManifestAst(migrations));
  const manifestFile = Bun.file(manifestPath);
  const current = (await manifestFile.exists()) ? await manifestFile.text() : undefined;
  if (current === output) {
    return { changed: false, migrations: migrations.length };
  }

  await Bun.write(manifestPath, output);
  return { changed: true, migrations: migrations.length };
}

function createManifestAst(migrations: readonly MigrationInput[]): ts.SourceFile {
  const imports = migrations.map(({ file }, index) =>
    factory.createImportDeclaration(
      undefined,
      factory.createImportClause(undefined, factory.createIdentifier(migrationIdentifier(index)), undefined),
      factory.createStringLiteral(`./migrations/${file}?raw`),
    ),
  );
  const migrationType = factory.createTypeAliasDeclaration(
    [exportModifier],
    "Migration",
    undefined,
    factory.createTypeLiteralNode([
      readonlyProperty("version", ts.SyntaxKind.NumberKeyword),
      readonlyProperty("file", ts.SyntaxKind.StringKeyword),
      readonlyProperty("sha256", ts.SyntaxKind.StringKeyword),
      readonlyProperty("sql", ts.SyntaxKind.StringKeyword),
    ]),
  );
  const migrationArray = factory.createVariableStatement(
    [exportModifier],
    factory.createVariableDeclarationList(
      [
        factory.createVariableDeclaration(
          "MIGRATIONS",
          undefined,
          factory.createTypeOperatorNode(
            ts.SyntaxKind.ReadonlyKeyword,
            factory.createArrayTypeNode(factory.createTypeReferenceNode("Migration")),
          ),
          factory.createArrayLiteralExpression(
            migrations.map(({ version, file, sha256 }, index) =>
              factory.createObjectLiteralExpression(
                [
                  factory.createPropertyAssignment("version", factory.createNumericLiteral(version)),
                  factory.createPropertyAssignment("file", factory.createStringLiteral(file)),
                  factory.createPropertyAssignment("sha256", factory.createStringLiteral(sha256)),
                  factory.createPropertyAssignment("sql", factory.createIdentifier(migrationIdentifier(index))),
                ],
                true,
              ),
            ),
            true,
          ),
        ),
      ],
      ts.NodeFlags.Const,
    ),
  );
  const compiledVersion = factory.createVariableStatement(
    [exportModifier],
    factory.createVariableDeclarationList(
      [
        factory.createVariableDeclaration(
          "COMPILED_SCHEMA_VERSION",
          undefined,
          undefined,
          factory.createPropertyAccessExpression(factory.createIdentifier("MIGRATIONS"), "length"),
        ),
      ],
      ts.NodeFlags.Const,
    ),
  );
  const statements: ts.Statement[] = [...imports, migrationType, migrationArray, compiledVersion];
  statements[0] = ts.addSyntheticLeadingComment(
    statements[0] ?? migrationType,
    ts.SyntaxKind.SingleLineCommentTrivia,
    " Generated by `bun run build:migrations`. Do not edit.",
    true,
  );
  const sourceFile = ts.createSourceFile("migrations.manifest.ts", "", ts.ScriptTarget.Latest, false, ts.ScriptKind.TS);
  return factory.updateSourceFile(sourceFile, statements);
}

function readonlyProperty(name: string, kind: ts.KeywordTypeSyntaxKind): ts.PropertySignature {
  return factory.createPropertySignature([readonlyModifier], name, undefined, factory.createKeywordTypeNode(kind));
}

function migrationIdentifier(index: number): string {
  return `migration${index}Sql`;
}
