export {
  adoptRecoveredOwnership,
  encodeGrokMarker,
  encodeGrokOwnership,
  isCanonicalLoopbackOrigin,
  isBootstrapGrokJournal,
  isCompletedGrokRemoval,
  isIncompleteRebind,
  isNewerAdapter,
  parseGrokMarker,
  parseGrokOwnership,
  peekManagedFormat,
  recoverGrokOwnership,
  tryReadLeaf,
} from './ownership';
