import { describe, expect, test } from 'bun:test';

import { AiSdkProviderError } from '../../error';
import {
  createProviderV4SpeechInvoke,
  createProviderV4TranscribeInvoke,
  providerV4SupportsSpeech,
  providerV4SupportsTranscription,
} from './provider-v4-audio';

type SpeechCall = {
  readonly text: string;
  readonly voice?: string;
  readonly outputFormat?: string;
  readonly instructions?: string;
  readonly speed?: number;
  readonly language?: string;
  readonly providerOptions?: Record<string, Record<string, unknown>>;
  readonly abortSignal?: AbortSignal;
};

type TranscriptionCall = {
  readonly audio: Uint8Array | string;
  readonly mediaType: string;
  readonly providerOptions?: Record<string, Record<string, unknown>>;
  readonly abortSignal?: AbortSignal;
};

/** 'RIFF....WAVE': the byte prefix the AI SDK sniffs as `audio/wav`. */
const WAV_BYTES = new Uint8Array([82, 73, 70, 70, 0, 0, 0, 0, 87, 65, 86, 69]);
/** Sniffs as nothing, so the SDK falls back to its `audio/mp3` alias. */
const UNSNIFFABLE_BYTES = new Uint8Array([9, 9]);

function speechProvider(
  audio: Uint8Array,
  record?: (call: SpeechCall) => void,
): { speechModel: (modelId: string) => unknown } {
  return {
    speechModel: (modelId) => ({
      specificationVersion: 'v3',
      provider: 'stub',
      modelId,
      doGenerate: async (options: SpeechCall) => {
        record?.(options);
        return {
          audio,
          warnings: [],
          request: {},
          response: { timestamp: new Date(0), modelId, headers: {}, body: undefined },
        };
      },
    }),
  };
}

function transcriptionProvider(
  result: Record<string, unknown>,
  record?: (call: TranscriptionCall) => void,
  provider = 'stub',
): { transcriptionModel: (modelId: string) => unknown } {
  return {
    transcriptionModel: (modelId) => ({
      specificationVersion: 'v3',
      provider,
      modelId,
      doGenerate: async (options: TranscriptionCall) => {
        record?.(options);
        return {
          text: 'hello',
          segments: [],
          language: undefined,
          durationInSeconds: undefined,
          warnings: [],
          response: { timestamp: new Date(0), modelId, headers: {}, body: undefined },
          ...result,
        };
      },
    }),
  };
}

describe('createProviderV4SpeechInvoke', () => {
  test('returns the generated bytes and an IANA media type clients can play', async () => {
    const invoke = createProviderV4SpeechInvoke('stub', speechProvider(UNSNIFFABLE_BYTES) as never);

    const result = await invoke({ text: 'hi', voice: 'alloy' }, { modelId: 'tts-1' });

    expect(result.audio).toEqual(UNSNIFFABLE_BYTES);
    // The adapter puts this straight into the `content-type` response header, and
    // `audio/mp3` (the AI SDK's own fallback) is not a registered media type.
    expect(result.mediaType).toBe('audio/mpeg');
  });

  test('keeps a media type the AI SDK actually recognized', async () => {
    const invoke = createProviderV4SpeechInvoke('stub', speechProvider(WAV_BYTES) as never);

    const result = await invoke({ text: 'hi', outputFormat: 'wav' }, { modelId: 'tts-1' });

    expect(result.mediaType).toBe('audio/wav');
  });

  test('forwards every speech option the invocation carries', async () => {
    const calls: SpeechCall[] = [];
    const controller = new AbortController();
    const invoke = createProviderV4SpeechInvoke(
      'stub',
      speechProvider(UNSNIFFABLE_BYTES, (call) => calls.push(call)) as never,
    );

    await invoke(
      {
        text: 'hi',
        voice: 'nova',
        outputFormat: 'opus',
        instructions: 'speak slowly',
        speed: 1.25,
        language: 'en',
        providerOptions: { openai: { foo: 'bar' } },
      },
      { modelId: 'tts-1', signal: controller.signal },
    );

    expect(calls[0]).toMatchObject({
      text: 'hi',
      voice: 'nova',
      outputFormat: 'opus',
      instructions: 'speak slowly',
      speed: 1.25,
      language: 'en',
      providerOptions: { openai: { foo: 'bar' } },
      abortSignal: controller.signal,
    });
  });

  test('resolves the speech model with the routed model id, not the client one', async () => {
    const calls: string[] = [];
    const invoke = createProviderV4SpeechInvoke('stub', {
      speechModel: (modelId: string) => {
        calls.push(modelId);
        return {
          specificationVersion: 'v3',
          provider: 'stub',
          modelId,
          doGenerate: async () => ({
            audio: UNSNIFFABLE_BYTES,
            warnings: [],
            response: { timestamp: new Date(0), modelId, headers: {}, body: undefined },
          }),
        };
      },
    } as never);

    await invoke({ text: 'hi' }, { modelId: 'gpt-4o-mini-tts' });

    expect(calls).toEqual(['gpt-4o-mini-tts']);
  });

  test('fails with a clear provider error when speech is unsupported', async () => {
    const invoke = createProviderV4SpeechInvoke('stub', {} as never);

    await expect(invoke({ text: 'hi' }, { modelId: 'tts-1' })).rejects.toThrow(
      "Provider 'stub' does not support speech generation",
    );
  });

  test('wraps upstream speech failures so cooldowns and status mapping can read them', async () => {
    const invoke = createProviderV4SpeechInvoke('stub', {
      speechModel: () => ({
        specificationVersion: 'v3',
        provider: 'stub',
        modelId: 'tts-1',
        doGenerate: async () => {
          throw new Error('upstream speech failed');
        },
      }),
    } as never);

    const error = await invoke({ text: 'hi' }, { modelId: 'tts-1' }).catch((caught: unknown) => caught);

    expect(error).toBeInstanceOf(AiSdkProviderError);
    expect(error).toMatchObject({ providerId: 'stub', message: expect.stringContaining('upstream speech failed') });
  });
});

describe('createProviderV4TranscribeInvoke', () => {
  test('returns text, segments, language, and duration', async () => {
    const invoke = createProviderV4TranscribeInvoke(
      'stub',
      transcriptionProvider({
        text: 'hello',
        segments: [{ text: 'hello', startSecond: 0, endSecond: 1 }],
        language: 'en',
        durationInSeconds: 1,
      }) as never,
    );

    const result = await invoke({ audio: WAV_BYTES, mediaType: 'audio/wav' }, { modelId: 'whisper-1' });

    expect(result.text).toBe('hello');
    expect(result.segments).toEqual([{ text: 'hello', startSecond: 0, endSecond: 1 }]);
    expect(result.language).toBe('en');
    expect(result.durationInSeconds).toBe(1);
  });

  test('reports no segments as an empty list so verbose_json egress can render', async () => {
    const invoke = createProviderV4TranscribeInvoke('stub', transcriptionProvider({ segments: undefined }) as never);

    const result = await invoke({ audio: WAV_BYTES }, { modelId: 'gpt-4o-transcribe' });

    expect(result.segments).toEqual([]);
    expect(result).not.toHaveProperty('language');
    expect(result).not.toHaveProperty('durationInSeconds');
  });

  test("forwards the client's declared media type instead of the SDK's byte guess", async () => {
    const calls: TranscriptionCall[] = [];
    const invoke = createProviderV4TranscribeInvoke(
      'stub',
      transcriptionProvider({}, (call) => calls.push(call)) as never,
    );

    // Upstream derives the upload filename extension from this, so guessing
    // `audio/wav` for an m4a upload makes OpenAI reject the file.
    await invoke({ audio: UNSNIFFABLE_BYTES, mediaType: 'audio/mp4' }, { modelId: 'whisper-1' });

    expect(calls[0]?.mediaType).toBe('audio/mp4');
  });

  test('falls back to the sniffed media type when the client declared none', async () => {
    const calls: TranscriptionCall[] = [];
    const invoke = createProviderV4TranscribeInvoke(
      'stub',
      transcriptionProvider({}, (call) => calls.push(call)) as never,
    );

    await invoke({ audio: WAV_BYTES }, { modelId: 'whisper-1' });

    expect(calls[0]?.mediaType).toBe('audio/wav');
  });

  // Plenty of HTTP clients label every multipart upload `application/octet-stream`.
  // Honouring that would make @ai-sdk/openai name the file `audio.octet-stream`,
  // which upstream rejects even for a recognizable WAV.
  test.each(['application/octet-stream', 'binary/octet-stream', ''] as const)(
    'ignores the generic upload type %p and lets the SDK sniff',
    async (mediaType) => {
      const calls: TranscriptionCall[] = [];
      const invoke = createProviderV4TranscribeInvoke(
        'stub',
        transcriptionProvider({}, (call) => calls.push(call)) as never,
      );

      await invoke({ audio: WAV_BYTES, mediaType }, { modelId: 'whisper-1' });

      expect(calls[0]?.mediaType).toBe('audio/wav');
    },
  );

  // MP4 and WebM are audio/video dual-purpose containers, so a recording uploaded
  // as `.mp4` routinely arrives declared `video/mp4`. Sniffing cannot recover it
  // (the `ftyp` box sits past where the SDK looks), and both are supported
  // transcription formats upstream, so the declared type must win here too.
  test.each([
    ['video/mp4', 'audio/mp4'],
    ['video/webm', 'audio/webm'],
  ] as const)('keeps the dual-purpose container type %p', async (mediaType, expected) => {
    const calls: TranscriptionCall[] = [];
    const invoke = createProviderV4TranscribeInvoke(
      'stub',
      transcriptionProvider({}, (call) => calls.push(call)) as never,
    );

    await invoke({ audio: UNSNIFFABLE_BYTES, mediaType }, { modelId: 'whisper-1' });

    expect(calls[0]?.mediaType).toBe(expected);
  });

  // @ai-sdk/openai turns the media type into the upload's filename extension, and
  // its table knows only a handful of subtypes — `audio/x-mp3` forwarded as
  // written becomes `audio.x-mp3`, which OpenAI rejects. Each alias must reach
  // the transport as the spelling that table maps correctly.
  test.each([
    ['audio/x-m4a', 'audio/mp4'],
    ['audio/m4a', 'audio/mp4'],
    ['audio/x-mp3', 'audio/mpeg'],
    ['audio/mp3', 'audio/mpeg'],
    ['audio/mpga', 'audio/mpeg'],
    ['audio/wave', 'audio/wav'],
    ['AUDIO/X-FLAC', 'audio/flac'],
  ] as const)('normalizes the supported alias %p to %p', async (mediaType, expected) => {
    const calls: TranscriptionCall[] = [];
    const invoke = createProviderV4TranscribeInvoke(
      'stub',
      transcriptionProvider({}, (call) => calls.push(call)) as never,
    );

    await invoke({ audio: UNSNIFFABLE_BYTES, mediaType }, { modelId: 'whisper-1' });

    expect(calls[0]?.mediaType).toBe(expected);
  });

  // An `audio/` prefix is not by itself evidence of a format OpenAI accepts, and
  // honouring an unknown subtype names the upload `audio.aiff` / `audio.*`.
  test.each(['audio/aiff', 'audio/*', 'audio/vnd.wave;codec=1'] as const)(
    'ignores the unsupported audio subtype %p and lets the SDK sniff',
    async (mediaType) => {
      const calls: TranscriptionCall[] = [];
      const invoke = createProviderV4TranscribeInvoke(
        'stub',
        transcriptionProvider({}, (call) => calls.push(call)) as never,
      );

      await invoke({ audio: WAV_BYTES, mediaType }, { modelId: 'whisper-1' });

      expect(calls[0]?.mediaType).toBe('audio/wav');
    },
  );

  // The declared type is consulted first, so an alias the table maps to a
  // container must not shadow a filename that names the same one differently.
  test('prefers the normalized declared alias over the filename', async () => {
    const calls: TranscriptionCall[] = [];
    const invoke = createProviderV4TranscribeInvoke(
      'stub',
      transcriptionProvider({}, (call) => calls.push(call)) as never,
    );

    await invoke(
      { audio: UNSNIFFABLE_BYTES, mediaType: 'audio/x-m4a', filename: 'clip.webm' },
      {
        modelId: 'whisper-1',
      },
    );

    expect(calls[0]?.mediaType).toBe('audio/mp4');
  });

  // A part with no `Content-Type`, or the generic one, still names the file. For
  // the containers sniffing cannot recover, that name is the only signal left —
  // without it an `.m4a` reaches OpenAI as `audio.wav` and is rejected.
  test.each([
    ['recording.m4a', undefined, 'audio/mp4'],
    ['recording.M4A', 'application/octet-stream', 'audio/mp4'],
    ['clip.webm', undefined, 'audio/webm'],
  ] as const)(
    'derives the container from the filename %p when the declared type says nothing',
    async (filename, mediaType, expected) => {
      const calls: TranscriptionCall[] = [];
      const invoke = createProviderV4TranscribeInvoke(
        'stub',
        transcriptionProvider({}, (call) => calls.push(call)) as never,
      );

      await invoke(
        { audio: UNSNIFFABLE_BYTES, filename, ...(mediaType === undefined ? {} : { mediaType }) },
        { modelId: 'whisper-1' },
      );

      expect(calls[0]?.mediaType).toBe(expected);
    },
  );

  // Every other accepted format has a magic prefix the SDK recognizes, so the
  // bytes beat a name the client chose — a `.mp3` extension on WAV bytes must
  // not relabel the upload.
  test('lets sniffing win over an extension it can already recognize', async () => {
    const calls: TranscriptionCall[] = [];
    const invoke = createProviderV4TranscribeInvoke(
      'stub',
      transcriptionProvider({}, (call) => calls.push(call)) as never,
    );

    await invoke({ audio: WAV_BYTES, filename: 'recording.mp3' }, { modelId: 'whisper-1' });

    expect(calls[0]?.mediaType).toBe('audio/wav');
  });

  test('forwards provider options and the abort signal', async () => {
    const calls: TranscriptionCall[] = [];
    const controller = new AbortController();
    const invoke = createProviderV4TranscribeInvoke(
      'stub',
      transcriptionProvider({}, (call) => calls.push(call)) as never,
    );

    await invoke(
      { audio: WAV_BYTES, providerOptions: { openai: { temperature: 0 } } },
      { modelId: 'whisper-1', signal: controller.signal },
    );

    expect(calls[0]).toMatchObject({
      providerOptions: { openai: { temperature: 0 } },
      abortSignal: controller.signal,
    });
  });

  test('carries the transcription controls under the provider-derived options key', async () => {
    const calls: TranscriptionCall[] = [];
    const invoke = createProviderV4TranscribeInvoke(
      'stub',
      // `openai.transcription` is the real @ai-sdk/openai value, and it parses its
      // options under `openai` — the first segment is what the SDK expects.
      transcriptionProvider({}, (call) => calls.push(call), 'openai.transcription') as never,
    );

    await invoke(
      {
        audio: WAV_BYTES,
        language: 'ja',
        prompt: 'proper nouns',
        temperature: 0.2,
        timestampGranularities: ['word', 'segment'],
      },
      { modelId: 'whisper-1' },
    );

    expect(calls[0]?.providerOptions).toEqual({
      openai: {
        language: 'ja',
        prompt: 'proper nouns',
        temperature: 0.2,
        timestampGranularities: ['word', 'segment'],
      },
    });
  });

  test('lets caller-supplied provider options win over the derived ones', async () => {
    const calls: TranscriptionCall[] = [];
    const invoke = createProviderV4TranscribeInvoke(
      'stub',
      transcriptionProvider({}, (call) => calls.push(call), 'groq') as never,
    );

    await invoke(
      { audio: WAV_BYTES, language: 'ja', providerOptions: { groq: { language: 'en', foo: 'bar' } } },
      { modelId: 'whisper-large-v3' },
    );

    expect(calls[0]?.providerOptions).toEqual({ groq: { language: 'en', foo: 'bar' } });
  });

  test('fails with a clear provider error when transcription is unsupported', async () => {
    const invoke = createProviderV4TranscribeInvoke('stub', {} as never);

    await expect(invoke({ audio: WAV_BYTES }, { modelId: 'whisper-1' })).rejects.toThrow(
      "Provider 'stub' does not support transcription",
    );
  });

  test('wraps upstream transcription failures so cooldowns and status mapping can read them', async () => {
    const invoke = createProviderV4TranscribeInvoke('stub', {
      transcriptionModel: () => ({
        specificationVersion: 'v3',
        provider: 'stub',
        modelId: 'whisper-1',
        doGenerate: async () => {
          throw new Error('upstream transcription failed');
        },
      }),
    } as never);

    const error = await invoke({ audio: WAV_BYTES }, { modelId: 'whisper-1' }).catch((caught: unknown) => caught);

    expect(error).toBeInstanceOf(AiSdkProviderError);
    expect(error).toMatchObject({
      providerId: 'stub',
      message: expect.stringContaining('upstream transcription failed'),
    });
  });
});

describe('capability probes', () => {
  test('a provider exposing the audio method is usable and one without it is not', () => {
    expect(providerV4SupportsSpeech(speechProvider(UNSNIFFABLE_BYTES) as never)).toBe(true);
    expect(providerV4SupportsSpeech({} as never)).toBe(false);
    expect(providerV4SupportsTranscription(transcriptionProvider({}) as never)).toBe(true);
    expect(providerV4SupportsTranscription({} as never)).toBe(false);
  });

  test('speech and transcription support are probed independently', () => {
    const speechOnly = speechProvider(UNSNIFFABLE_BYTES) as never;
    const transcriptionOnly = transcriptionProvider({}) as never;

    expect(providerV4SupportsTranscription(speechOnly)).toBe(false);
    expect(providerV4SupportsSpeech(transcriptionOnly)).toBe(false);
  });
});
