import { readdirSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

export const listAssetPaths = (distDir: string): string[] =>
  readdirSync(distDir, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile())
    .map((entry) => relative(distDir, join(entry.parentPath, entry.name)).split(sep).join("/"))
    .sort();

export const renderCompiledEntry = (assetPaths: readonly string[]): string => {
  const lines = [
    "// Generated by scripts/generate-compiled-entry.ts - do not edit, do not commit.",
    ...assetPaths.map(
      (path, index) => `import asset${index} from "@aio-proxy/dashboard/dist/${path}" with { type: "file" };`,
    ),
    'import { embeddedDashboardAssets } from "./dashboard-assets";',
    'import { main } from "./main";',
    "",
    "const files: Readonly<Record<string, string>> = {",
    ...assetPaths.map((path, index) => `  "${path}": asset${index},`),
    "};",
    "",
    "await main({ dashboardAssets: () => embeddedDashboardAssets(files) });",
    "",
  ];
  return lines.join("\n");
};

export const dashboardDistDir = (): string =>
  join(fileURLToPath(import.meta.resolve("@aio-proxy/dashboard/dist/index.html")), "..");

export const compiledEntryPath = (): string => join(import.meta.dir, "..", "src", "main.compiled.gen.ts");

export const virtualCompiledEntry = (
  assetPaths: readonly string[] = listAssetPaths(dashboardDistDir()),
): { readonly entrypoint: string; readonly files: Record<string, string> } => {
  const entrypoint = compiledEntryPath();
  return {
    entrypoint,
    files: {
      [entrypoint]: renderCompiledEntry(assetPaths),
    },
  };
};

if (import.meta.main) {
  console.log(virtualCompiledEntry().entrypoint);
}
