import { readdirSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

export const listAssetPaths = (distDir: string): string[] =>
  readdirSync(distDir, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile())
    .map((entry) => relative(distDir, join(entry.parentPath, entry.name)).split(sep).join("/"))
    .sort();

export const renderCompiledEntry = (assetPaths: readonly string[]): string => {
  const imports = assetPaths
    .map((path, index) => `import asset${index} from "@aio-proxy/dashboard/dist/${path}" with { type: "file" };`)
    .join("\n");
  const entries = assetPaths.map((path, index) => `  "${path}": asset${index},`).join("\n");
  return `// Generated by scripts/generate-compiled-entry.ts — do not edit, do not commit.
${imports}
import { embeddedDashboardAssets } from "./dashboard-assets";
import { main } from "./main";

const files: Readonly<Record<string, string>> = {
${entries}
};

await main({ dashboardAssets: () => embeddedDashboardAssets(files) });
`;
};

export const generateCompiledEntry = (): string => {
  const distDir = join(fileURLToPath(import.meta.resolve("@aio-proxy/dashboard/dist/index.html")), "..");
  const outFile = join(import.meta.dir, "..", "src", "main.compiled.gen.ts");
  writeFileSync(outFile, renderCompiledEntry(listAssetPaths(distDir)));
  return outFile;
};

if (import.meta.main) {
  console.log(generateCompiledEntry());
}
