// Generated by `bun run build:migrations`. Do not edit.
import migration0Sql from "./migrations/0000_busy_hedge_knight.sql?raw";
import migration1Sql from "./migrations/0001_violet_mentallo.sql?raw";
export type Migration = {
    readonly version: number;
    readonly file: string;
    readonly sha256: string;
    readonly sql: string;
};
export const MIGRATIONS: readonly Migration[] = [
    {
        version: 1,
        file: "0000_busy_hedge_knight.sql",
        sha256: "15813487f2b722358332d79e093025352a1399111e0983b8015fe8b8884f2681",
        sql: migration0Sql
    },
    {
        version: 2,
        file: "0001_violet_mentallo.sql",
        sha256: "f2ac8491c8d999f81370a06a77e895dabc8c717e382d1506ae77e3444764b8a6",
        sql: migration1Sql
    }
];
export const COMPILED_SCHEMA_VERSION = MIGRATIONS.length;
