// Generated by `bun run build:migrations`. Do not edit.
import migration0Sql from "./migrations/0000_busy_hedge_knight.sql?raw";
import migration1Sql from "./migrations/0001_easy_logan.sql?raw";
import migration2Sql from "./migrations/0002_orange_leper_queen.sql?raw";
import migration3Sql from "./migrations/0003_charming_maginty.sql?raw";
export type Migration = {
    readonly version: number;
    readonly file: string;
    readonly sha256: string;
    readonly sql: string;
};
export const MIGRATIONS: readonly Migration[] = [
    {
        version: 1,
        file: "0000_busy_hedge_knight.sql",
        sha256: "15813487f2b722358332d79e093025352a1399111e0983b8015fe8b8884f2681",
        sql: migration0Sql
    },
    {
        version: 2,
        file: "0001_easy_logan.sql",
        sha256: "26b13dbe017897f1c838d11b621164a6219f630330ae34991cf18dcd0105e778",
        sql: migration1Sql
    },
    {
        version: 3,
        file: "0002_orange_leper_queen.sql",
        sha256: "346f578dff1bdae80a96b8404bf77edb3c4537f657bf723b5ccc3924da531ade",
        sql: migration2Sql
    },
    {
        version: 4,
        file: "0003_charming_maginty.sql",
        sha256: "1537817c61f34c66b820390060d9b772a6b29da52c9333dd4ddce8501489ad75",
        sql: migration3Sql
    }
];
export const COMPILED_SCHEMA_VERSION = MIGRATIONS.length;
